# Generated by Django 3.0.14 on 2023-07-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230701_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content03',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='sub_heading03',
            field=models.CharField(default='', max_length=500),
        ),
    ]
