# Generated by Django 3.0.14 on 2023-07-01 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20230702_0115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='sub_heading01',
            new_name='heading01',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='sub_heading02',
            new_name='heading02',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='sub_heading03',
            new_name='heading03',
        ),
    ]
