# Generated by Django 3.0.14 on 2023-07-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpost_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='whole_content',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content01',
            field=models.CharField(default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content02',
            field=models.CharField(default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content03',
            field=models.CharField(default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='heading01',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='heading02',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='heading03',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='blog/images'),
        ),
    ]
