# Generated by Django 3.0.14 on 2023-07-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20230707_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='intro',
            field=models.CharField(max_length=900),
        ),
    ]
