# Generated by Django 3.0.14 on 2023-06-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20230625_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=50)),
                ('query', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='contact',
        ),
    ]
