# Generated by Django 3.0.14 on 2023-06-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20230626_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('placed_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_ids', models.CharField(default='', max_length=5000)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('Address01', models.CharField(default='', max_length=500)),
                ('Address02', models.CharField(default='', max_length=500)),
                ('city', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=15)),
                ('pin_code', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='contacts',
            new_name='contact',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
