# Generated by Django 3.0.14 on 2023-06-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20230626_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_ids',
            field=models.CharField(max_length=5000),
        ),
    ]
