# Generated by Django 3.0.14 on 2023-06-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20230626_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker_id', models.IntegerField()),
                ('phone', models.CharField(default='', max_length=15)),
                ('status', models.CharField(default='', max_length=5000)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
