# Generated by Django 3.0.14 on 2023-06-27 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20230627_1619'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tracker',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
    ]
