# Generated by Django 3.0.14 on 2023-06-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20230627_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker_id', models.IntegerField(default='')),
                ('timeStamp', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='', max_length=5000)),
            ],
        ),
    ]
