# Generated by Django 3.0.14 on 2023-06-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_tracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='tracker_id',
            field=models.IntegerField(default=0),
        ),
    ]
