# Generated by Django 3.0.14 on 2023-07-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_order_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='query',
            field=models.TextField(default=''),
        ),
    ]
